### ISSUE TITLE
Ubicación de aventuras

### ISSUE THREAD

**Issue by Federico-G** [RungeKutta2/Khoeli#13]
Las aventuras deberían estar bien ubicadas. Ahora solo tienen una que es la de pruebas creo, pero de todas maneras no debería estar en la raíz del proyecto

https://github.com/RungeKutta2/Khoeli/blob/master/test.json

**Comment by lsantosferreiro** [comment]
Las aventuras ahora están ubicadas en una carpeta individual

**Comment by Federico-G** [comment]
👍
